const pages=['Visão Geral','Mapa','Arranjos Populacionais','Municípios','Série Histórica','Empreendimentos','Tipologias','Agentes','Grupos Econômicos','Comparador','Rankings'];
const desc={Mapa:'Explore São Paulo, os arranjos populacionais e os municípios sobre o mapa-base OpenStreetMap.', 'Arranjos Populacionais':'Comparação dos quatro recortes prioritários com preservação dos municípios componentes.',Municípios:'Explore os municípios do Estado presentes no banco e abra um perfil municipal.', 'Série Histórica':'Quatro séries com cronologias próprias; cancelados com corte pelo ano de entrada.',Empreendimentos:'Registros individuais da base analítica; cada linha é um processo, sem pressupor implantação.',Tipologias:'Composição das propostas por modalidade de empreendimento.',Agentes:'Proprietários originais, nomes normalizados e trajetórias individuais sem fundir SPEs.', 'Grupos Econômicos':'Agrupamentos econômicos candidatos documentados; vínculos societários não comprovados nesta base.',Regulação:'Estrutura de pesquisa para incorporar marcos municipais, zoneamento, perímetros e planos diretores em etapas posteriores.',Comparador:'Compare simultaneamente municípios, APs ou proprietários normalizados.',Metodologia:'Definições, cobertura, limitações e conferência com a aba 26_Validacao da base v2.', 'Dados/Downloads':'Bases de referência e exportação dos resultados filtrados.'};
const $=id=>document.getElementById(id),fmt=n=>Math.round(n||0).toLocaleString('pt-BR'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data=[],validation=[],page='Visão Geral',compare=[],indicatorsCollapsed=false;
const aps=['AP Bauru','AP São José do Rio Preto','AP São José dos Campos','AP Sorocaba'];const ix={city:1,ap:2,type:3,name:5,original:6,owner:7,group:8,uh:9,status:10,prot:11,cert:12,area:13,id:14,address:15,lots:16,modality:17,disp:18,cancel:19,conflict:20};
function options(id,vals,first='Todos'){let e=$(id),old=e.value;e.innerHTML='<option value="">'+first+'</option>'+vals.filter(Boolean).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR')).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(vals.includes(old))e.value=old}
const unique=i=>[...new Set(data.map(r=>r[i]).filter(Boolean))];function params(){return Object.fromEntries(['ap','city','start','end','situation','type','owner','group'].map(k=>[k,$(k).value]))}
function base(r,p){return (!p.ap||r[ix.ap]===p.ap)&&(!p.city||r[ix.city]===p.city)&&(!p.type||r[ix.type]===p.type)&&(!p.owner||r[ix.owner]===p.owner)&&(!p.group||r[ix.group]===p.group)&&(!p.situation||r[ix.status]===p.situation)}
function slices(){let p=params(),min=+p.start||1991,max=+p.end||2026;let b=data.filter(r=>base(r,p));return {p:b.filter(r=>r[ix.prot]>=min&&r[ix.prot]<=max),c:b.filter(r=>r[ix.status]==='Certificado'&&r[ix.cert]>=min&&r[ix.cert]<=max),d:b.filter(r=>r[ix.status]==='Dispensado'&&r[ix.disp]>=min&&r[ix.disp]<=max),k:b.filter(r=>r[ix.status]==='Cancelados'&&r[ix.cancel]>=min&&r[ix.cancel]<=max)}}

const sum=(rows,i)=>rows.reduce((a,r)=>a+(+r[i]||0),0);const area=r=>+r[ix.area]||0;const areaRows=r=>r.filter(x=>area(x)>0);function aggregate(rows,i){let m=new Map;rows.forEach(r=>{let k=r[i]||'Sem informação';let v=m.get(k)||{name:k,uh:0,count:0};v.uh+=+r[ix.uh]||0;v.count++;m.set(k,v)});return [...m.values()].sort((a,b)=>b.uh-a.uh)}
function metrics(s){return `<section class="panel indicators-panel"><button class="section-toggle indicator-toggle" aria-expanded="${!indicatorsCollapsed}"><span>Indicadores do recorte</span><span class="chevron" aria-hidden="true">${indicatorsCollapsed?"⌄":"⌃"}</span></button><div class="indicator-body" ${indicatorsCollapsed?"hidden":""}>${table(['Métrica','Protocolados','Certificados','Dispensados','Cancelados'],[['Empreendimentos / registros','count'],['UH',ix.uh],['Lotes',ix.lots]].map(([label,col])=>`<tr><td>${label}</td>${['p','c','d','k'].map(st=>`<td class="num">${fmt(col==='count'?s[st].length:sum(s[st],col))}</td>`).join('')}</tr>`))}<details><summary>Como interpretar as quatro colunas</summary><p class="muted">Protocolados são entradas e incluem as situações posteriores: as quatro colunas não devem ser somadas. Certificados representam a certificação pelo colegiado; dispensados são declarações de não enquadramento. Cancelados usam o ano de entrada, pois não há data própria de cancelamento. UH e lotes são propostas registradas, sem comprovação de implantação.</p></details></div></section>`}
function areaReport(s){return table(['Série','Área de gleba conhecida · m²','Registros com área','Registros totais','Cobertura'],['p','c','d','k'].map((st,i)=>{let a=areaRows(s[st]);return `<tr><td>${['Protocolados','Certificados','Dispensados','Cancelados'][i]}</td><td class="num">${a.length?fmt(sum(a,ix.area)):"—"}</td><td class="num">${fmt(a.length)}</td><td class="num">${fmt(s[st].length)}</td><td class="num">${s[st].length?Math.round(a.length/s[st].length*100)+'%':'—'}</td></tr>`}))}

function bars(items,n=10){let a=items.slice(0,n),m=Math.max(1,...a.map(x=>x.uh));return `<div class="bars">${a.length?a.map(x=>`<div class="barrow"><label title="${esc(x.name)}">${esc(x.name)}</label><div class="track"><div class="fill" style="width:${x.uh/m*100}%"></div></div><strong class="num">${fmt(x.uh)}</strong></div>`).join(''):'<p class="muted">Sem registros para este recorte.</p>'}</div>`}
function series(s,property=null,value=null,metric=ix.uh){let y=Array.from({length:36},(_,j)=>1991+j);let eventcols={p:ix.prot,c:ix.cert,d:ix.disp,k:ix.cancel},out={y};for(let st of ['p','c','d','k'])out[st]=y.map(t=>sum((s[st]||[]).filter(r=>r[eventcols[st]]===t&&(!property||r[property]===value)),metric));return out}

function chart(z,sharedMax=0){const keys=['p','c','d','k'],labels=['Protocolados','Certificados','Dispensados','Cancelados'],colors=['#28758a','#bc8652','#756497','#ac5960'];const max=Math.max(1,sharedMax,...keys.flatMap(k=>z[k]||[])),W=1100,H=300,left=75,right=15,top=20,bottom=40,step=(W-left-right)/z.y.length,bar=step*.19,yy=v=>H-bottom-v/max*(H-top-bottom);const ticks=z.y.filter(y=>y===z.y[0]||y===z.y.at(-1)||y%5===0);return `<div class="legend">${labels.map((label,j)=>`<span><i style="background:${colors[j]}"></i>${label}</span>`).join('')}</div><div class="chart-scroll"><svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Barras verticais anuais das quatro séries">${[0,.25,.5,.75,1].map(t=>`<line x1="${left}" y1="${yy(max*t)}" x2="${W-right}" y2="${yy(max*t)}" stroke="#dce5e9"/><text x="${left-8}" y="${yy(max*t)+4}" text-anchor="end" font-size="12" fill="#647b86">${fmt(max*t)}</text>`).join('')}${z.y.map((y,j)=>keys.map((key,k)=>{let v=(z[key]||[])[j]||0;return `<rect x="${left+j*step+step*.1+k*bar}" y="${yy(v)}" width="${bar}" height="${H-bottom-yy(v)}" fill="${colors[k]}"><title>${y} · ${labels[k]}: ${fmt(v)}</title></rect>`}).join('')).join('')}${ticks.map(y=>`<text x="${left+(z.y.indexOf(y)+.5)*step}" y="${H-12}" text-anchor="middle" font-size="12" fill="#647b86">${y}</text>`).join('')}</svg></div>`}
function panel(title,body,wide=false){return `<section class="panel ${wide?'wide':''}"><h2>${title}</h2>${body}</section>`}function table(headers,rows){return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th class="${/^(Protocolados|Certificados|Dispensados|Cancelados|UH |Lotes$)/.test(h)?"num":""}">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}function rowAgg(a,action=''){return `<tr><td>${action?`<button class="link" data-open="${action}" data-value="${esc(a.name)}">${esc(a.name)}</button>`:esc(a.name)}</td><td class="num">${fmt(a.uh)}</td><td class="num">${fmt(a.count)}</td></tr>`}
function download(rows,name){let cols=['Município','AP','Tipo','Empreendimento','Proprietário original','Proprietário normalizado','Grupo candidato','UH','Situação','Ano protocolo','Ano certificado','Lotes','Modalidade','Ano dispensa','Ano entrada dos cancelados','Conflito municipal','ID'];let ids=[1,2,3,5,6,7,8,9,10,11,12,16,17,18,19,20,14];let csv=[cols,...rows.map(r=>ids.map(i=>r[i]??''))].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');let url=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function render(){disposeTerritoryMap();let s=slices(),p=params();$('title').textContent=page;$('intro').textContent=desc[page]||'Examine protocolos, certificados e agentes no território paulista.';$('status').textContent='';$('status').hidden=true;$('nav').innerHTML=pages.map(n=>`<button class="${n===page?'active':''}" data-page="${n}">${n}</button>`).join('');let z=series(s),out=metrics(s);let city=aggregate(s.p,ix.city),ap=aggregate(s.p,ix.ap),typ=aggregate(s.p,ix.type),owners=aggregate(s.p,ix.owner),groups=aggregate(s.p.filter(r=>r[ix.group]),ix.group);
if(page==='Visão Geral')out+=`<div class="grid">${panel('Evolução anual · UH',chart(z),true)}${panel('Evolução anual · lotes',chart(series(s,null,null,ix.lots)),true)}${panel('Tipologias · UH protocoladas',bars(typ,4))}${panel('Municípios · UH protocoladas',bars(city,10))}</div>`;
if(page==='Mapa')out+=panel('Mapa interativo',`<div class="toolbar"><span id="map-selection" role="status">Carregando limites municipais…</span><button class="button" id="map-reset">Reenquadrar seleção</button></div><div id="territory-map" aria-label="Mapa interativo dos municípios de São Paulo"></div><p class="muted">Use os filtros para enquadrar o estado, um AP ou um município. Arraste para navegar e use +/− para aproximar. Os limites representam municípios, sem localização dos empreendimentos.</p><p class="muted">Limites simplificados: <a href="https://servicodados.ibge.gov.br/api/docs/malhas?versao=3" target="_blank" rel="noopener">IBGE</a>, referência 2020. Mapa-base: <a href="https://www.openstreetmap.org/#map=7/-22.502/-49.653" target="_blank" rel="noopener">OpenStreetMap · ver ampliado</a>.</p>`,true)+panel('Municípios',bars(city,35),true);
if(page==='Arranjos Populacionais')out+=panel('Quatro arranjos prioritários',table(['Arranjo','UH protocoladas','Protocolos'],aps.map(a=>rowAgg(ap.find(x=>x.name===a)||{name:a,uh:0,count:0}))),true);
if(page==='Municípios')out+=panel('Municípios no banco',table(['Município','UH protocoladas','Protocolos'],city.map(a=>rowAgg(a,'city'))),true);
if(page==='Série Histórica')out+=panel('Quatro séries · UH por ano',chart(z)+table(['Ano','UH protocoladas','UH certificadas','UH dispensadas','UH canceladas'],z.y.map(y=>`<tr><td>${y}</td>${['p','c','d','k'].map(st=>`<td class="num">${fmt(z[st][y-1991])}</td>`).join('')}</tr>`)),true);
if(page==='Empreendimentos')out+=panel('Registros individuais',`<div class="toolbar"><span class="muted">Exibindo até 300 de ${fmt(s.p.length)} protocolos. O CSV exporta todos os registros filtrados.</span><button class="button" id="export">Baixar protocolos filtrados · CSV</button></div>${table(['Empreendimento','Município','Tipo','Proprietário original','UH','Situação','Ano entrada'],s.p.slice(0,300).map(r=>`<tr><td>${esc(r[ix.name])}</td><td>${esc(r[ix.city])}</td><td>${esc(r[ix.type])}</td><td>${esc(r[ix.original])}</td><td class="num">${fmt(r[ix.uh])}</td><td>${esc(r[ix.status])}</td><td>${r[ix.prot]||'—'}</td></tr>`))}`,true);
if(page==='Tipologias')out+=`<div class="grid">${panel('UH protocoladas',bars(typ,4))}${panel('UH certificadas',bars(aggregate(s.c,ix.type),4))}</div>`;
if(page==='Agentes')out+=panel('Proprietários normalizados',`<p class="muted">Clique em um nome para abrir sua trajetória. O nome original permanece em cada registro.</p>${table(['Proprietário normalizado','UH protocoladas','Protocolos'],owners.slice(0,250).map(a=>rowAgg(a,'owner')))}`,true);
if(page==='Grupos Econômicos')out+=panel('Grupos candidatos',`<p class="muted">Agrupamentos preexistentes na planilha. A ausência de grupo não implica ausência de vínculo. SPEs permanecem distintas na listagem de agentes.</p>${table(['Grupo candidato','UH protocoladas','Protocolos'],groups.map(a=>rowAgg(a,'group')))}`,true);
if(page==='Regulação')out+=panel('Linha de pesquisa regulatória',`<div class="chain">${['Condições territoriais e institucionais','Agentes / grupos / SPEs','Localização e tipologia','Protocolamento','Certificação','Implantação / produção espacial','Transformação urbana'].map((x,i)=>`${i?'<b>→</b>':''}<span>${x}</span>`).join('')}</div><p class="muted">Modelo analítico para testar relações, sem causalidade comprovada. A base atual não contém cronologia de leis, mapas de perímetro ou evidência de implantação. Documentos municipais serão incorporados com fonte, vigência, território e instrumento.</p>`,true);
if(page==='Rankings')out+=panel('Rankings integrados',`<div class="toolbar"><label>Dimensão <select id="rankdim"><option value="1">Municípios</option><option value="2">Arranjos populacionais</option><option value="3">Tipo de empreendimento</option><option value="17">Modalidade</option><option value="7">Proprietário normalizado</option><option value="8">Grupo candidato</option></select></label><label>Métrica <select id="rankmetric"><option value="9">UH</option><option value="16">Lotes</option><option value="count">Empreendimentos</option></select></label></div><div id="rankresult"></div>`,true);
if(page==='Área de Gleba')out+=panel('Área de gleba e cobertura',`<p class="muted">Área parcial associada aos registros. Não é área construída; processos distintos podem se referir à mesma gleba. Esta informação aparece nesta seção, sem repetir avisos nos rankings.</p>${areaReport(s)}`,true);
if(page==='Camadas e Fontes')out+=panel('Estrutura das futuras camadas',table(['Base','Camada / escala','Estado'],[['GRAPROHAB','Lotes, UH e processos por município/AP','Dados tabulares disponíveis; polígonos municipais a integrar'],['IBGE 2000, 2010, 2022','Universo: setores; amostra: áreas de ponderação','Integração planejada; compatibilização temporal necessária'],['Fundação João Pinheiro','Déficit e inadequação no recorte oficialmente divulgado','Integração planejada; não extrapolar UF/RM para setores'],['OpenStreetMap','Mapa-base, uso mapeado, edificações, transporte e vegetação','Integração planejada; cobertura variável e data de extração'],['Municípios','Zoneamento, perímetros, gabarito legal, planos diretores','Integração planejada; fonte e vigência por instrumento']].map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`))+`<p class="muted">Gabarito observado no OSM e gabarito permitido na lei são camadas diferentes. O CSV contém 6.498 registros com Xpos/Ypos, mas apenas 34 pares de coordenadas: não usar esses pares como localização exata de empreendimentos.</p>`,true);
if(page==='Comparador')out+=comparison(s);
if(page==='Metodologia')out+=methodology(s);
if(page==='Dados/Downloads')out+=panel('Arquivos e exportações',`<p><a class="button" href="assets/original-graprohab.zip" download>CSV original ZIP · auditoria</a> <a class="button" href="assets/base-ampliada-v2.xlsx" download>Excel ampliado · 31 abas</a> <a class="button" href="assets/base-analitica.xlsx" download>Excel anterior · referência</a> <a class="button" href="assets/metodologia.docx" download>Metodologia DOCX</a></p><p><button class="button" id="export">Protocolos filtrados · CSV</button> <button class="button" id="exportcert">Certificados filtrados · CSV</button></p><p class="muted">Hierarquia: CSV original → processamento documentado → Excel analítico → aplicação. A aplicação lê os registros individuais da base ampliada. As novas regras de dispensa, cancelamento, modalidade e chave municipal estão documentadas no Excel. O CSV original permanece disponível para auditoria.</p>`,true);
$('content').innerHTML=out;if(page==='Mapa')initTerritoryMap();document.querySelectorAll('.indicator-toggle').forEach(e=>e.onclick=()=>{indicatorsCollapsed=!indicatorsCollapsed;document.querySelectorAll('.indicator-toggle').forEach(b=>{b.setAttribute('aria-expanded',String(!indicatorsCollapsed));b.querySelector('.chevron').textContent=indicatorsCollapsed?'⌄':'⌃';b.nextElementSibling.hidden=indicatorsCollapsed})});document.querySelectorAll('[data-page]').forEach(e=>e.onclick=()=>{page=e.dataset.page;closeMenu();render()});document.querySelectorAll('[data-open]').forEach(e=>e.onclick=()=>{$(e.dataset.open).value=e.dataset.value;page=e.dataset.open==='city'?'Municípios':e.dataset.open==='owner'?'Agentes':'Grupos Econômicos';renderProfile(e.dataset.open,e.dataset.value)});if($('export'))$('export').onclick=()=>download(s.p,'graprohab_protocolados_filtrados.csv');if($('exportcert'))$('exportcert').onclick=()=>download(s.c,'graprohab_certificados_filtrados.csv');if($('rankdim')){let update=()=>{$('rankresult').innerHTML=rankingTable(s,+$('rankdim').value,$('rankmetric').value)};$('rankdim').onchange=update;$('rankmetric').onchange=update;update()}if($('addcompare'))$('addcompare').onclick=()=>{let v=$('comparisonPick').value;if(v&&!compare.includes(v)){compare.push(v);render()}};document.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{compare=compare.filter(x=>x!==e.dataset.remove);render()})}
function renderProfile(kind,value){render();let s=slices(),label=kind==='city'?'Município':kind==='owner'?'Proprietário normalizado':'Grupo candidato';$('content').insertAdjacentHTML('afterbegin',panel(`Perfil · ${esc(value)}`,`<p class="muted">${label}. Evolução temporal, território, tipologia e empreendimentos associados ao recorte atual.</p>${chart(series(s))}<div class="grid"><div>${panel('Municípios de atuação',bars(aggregate(s.p,ix.city),20))}</div><div>${panel('Arranjos e tipologias',bars(aggregate(s.p,ix.ap),8)+bars(aggregate(s.p,ix.type),4))}</div></div><p>UH protocoladas: <strong>${fmt(sum(s.p,ix.uh))}</strong> · UH certificadas: <strong>${fmt(sum(s.c,ix.uh))}</strong></p>${table(['Empreendimento','Proprietário original','Município','Tipo','UH'],s.p.slice(0,100).map(r=>`<tr><td>${esc(r[ix.name])}</td><td>${esc(r[ix.original])}</td><td>${esc(r[ix.city])}</td><td>${esc(r[ix.type])}</td><td class="num">${fmt(r[ix.uh])}</td></tr>`))}`,true))}
function comparison(s){let choices=[...aps.map(x=>['ap',x]),...unique(ix.city).map(x=>['city',x]),...unique(ix.owner).map(x=>['owner',x])];let options=choices.map(([k,v])=>`<option value="${esc(k+'|'+v)}">${k==='ap'?'AP':k==='city'?'Município':'Agente'} · ${esc(v)}</option>`).join('');let selected=compare.map(item=>{let [k,v]=item.split('|');return Object.fromEntries(['p','c','d','k'].map(st=>[st,s[st].filter(r=>r[ix[k]]===v)]))}),sharedMax=Math.max(1,...selected.flatMap(t=>{let z=series(t);return ['p','c','d','k'].flatMap(st=>z[st])}));let blocks=compare.map((item,index)=>{let [k,v]=item.split('|'),t=selected[index],p=t.p,c=t.c;return `<div class="panel"><div class="toolbar"><h2>${esc(v)}</h2><button class="button" data-remove="${esc(item)}">Remover</button></div><p>Protocoladas: <strong>${fmt(sum(p,ix.uh))} UH</strong> · Certificadas: <strong>${fmt(sum(c,ix.uh))} UH</strong></p>${metrics(t)}${chart(series(t),sharedMax)}</div>`}).join('');return panel('Seleção comparativa',`<div class="toolbar"><select id="comparisonPick" style="max-width:600px">${options}</select><button class="button" id="addcompare">Adicionar</button></div><p class="muted">Adicione dois ou mais recortes. Os filtros globais também se aplicam aos comparados. As quatro séries usam a mesma escala vertical entre os recortes.</p>`,true)+`<div class="compare">${blocks}</div>`}
function methodology(s){return panel('Definições e critérios',`<p>Protocolados: entradas dos quatro tipos; inclui situações posteriores e não é uma situação exclusiva. Certificados: situação exatamente Certificado, por data de certificação e fallback documentado. Dispensados: declaração de não enquadramento, por Data Do Certificado quando situação=Dispensado e fallback do ano de resultado. Cancelados: situação exatamente Cancelados, com corte pelo ano de entrada; a data de cancelamento não está disponível. A situação DISPENSADO/CANCELADO permanece ambígua.</p><p>UH usa Nº De Lotes Totais (Ver Obs) nos quatro tipos. Lotes exclui CONDOMÍNIO. A área de gleba e sua cobertura estão na seção própria. 2026 é parcial. Os 26.632 registros analíticos vêm de 26.637 registros originais.</p><p>Proprietários normalizados e grupos candidatos reaproveitam a planilha anterior; SPEs permanecem distintas. Agrupamento municipal usa Municipio original; conflitos de nome/código são auditados e não corrigidos definitivamente.</p><p><a href="https://app.habitacao.sp.gov.br/ManualGraprohab/RegimentoInterno.html" target="_blank" rel="noopener">Regimento GRAPROHAB — certificação, protocolo e cancelamento</a> · <a href="https://app.habitacao.sp.gov.br/ManualGraprohab/32Criterios.html" target="_blank" rel="noopener">Critérios de dispensa</a></p>`,true)+panel('Validação e conflito municipal',`<p class="muted">A planilha anterior usa Nomemunic para o total municipal. A nova leitura usa Municipio. O registro 14329 (521 UH/lotes, Cancelados, entrada 2016) aponta Rio Preto nesse campo, mas Rio Pardo no nome e código IBGE. A atribuição está pendente. A diferença preexistente de 18 UH entre Site e CSV é preservada, separada do conflito de 521.</p>${table(['Município','Lotes · coluna CSV anterior','Lotes · campo Municipio','UH · Site','UH · CSV anterior','UH · campo Municipio'],validation.map(v=>{let rows=data.filter(r=>r[ix.city]===v[0]);return `<tr><td>${esc(v[0])}</td><td>${fmt(v[2])}</td><td>${fmt(sum(rows,ix.lots))}</td><td>${fmt(v[4])}</td><td>${fmt(v[5])}</td><td>${fmt(sum(rows,ix.uh))}</td></tr>`}))}`,true)}

Promise.all([fetch('assets/records.json').then(r=>{if(!r.ok)throw Error('base');return r.json()}),fetch('assets/validation.json').then(r=>r.json())]).then(([a,v])=>{data=a.rows;validation=v;options('ap',aps);options('city',unique(ix.city));options('type',unique(ix.type));options('situation',unique(ix.status));options('owner',unique(ix.owner));options('group',unique(ix.group));['ap','city','type','situation','owner','group','start','end'].forEach(id=>$(id).addEventListener('change',render));$('clear').onclick=()=>{['ap','city','type','situation','owner','group'].forEach(k=>$(k).value='');$('start').value=1991;$('end').value=2026;render()};render()}).catch(e=>{$('status').hidden=false;$('status').textContent='Falha ao carregar os dados';$('content').innerHTML='<div class="notice">Não foi possível ler a base analítica. Abra a aplicação por um servidor HTTP e verifique assets/records.json.</div>';console.error(e)});

function rankingTable(s,dim,metric){let keys=[...new Set([...s.p,...s.c,...s.d,...s.k].map(r=>r[dim]||'Sem informação').filter(name=>![ix.ap,ix.group].includes(dim)||name!=='Sem informação'))],value=(rows)=>metric==='count'?rows.length:sum(rows,+metric);let rows=keys.map(name=>({name,values:['p','c','d','k'].map(st=>value(s[st].filter(r=>(r[dim]||'Sem informação')===name)))})).sort((a,b)=>b.values[0]-a.values[0]||a.name.localeCompare(b.name,'pt-BR'));return `<p class="muted">Posição por volume protocolado; as demais situações têm eixos temporais próprios. Exibindo até 300 posições.${dim===ix.ap?` Municípios fora dos quatro APs prioritários: ${fmt(s.p.filter(r=>!r[dim]).length)} registros protocolados, fora deste ranking.`:dim===ix.group?` Sem grupo candidato associado: ${fmt(s.p.filter(r=>!r[dim]).length)} registros protocolados, fora deste ranking.`:""}</p>`+table(['Ranking','Dimensão','Protocolados','Certificados','Dispensados','Cancelados'],rows.slice(0,300).map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td>${r.values.map(v=>`<td class="num">${fmt(v)}</td>`).join('')}</tr>`))}

function closeMenu(){document.getElementById('nav').hidden=true;document.getElementById('menu-toggle').setAttribute('aria-expanded','false');document.getElementById('menu-toggle').setAttribute('aria-label','Abrir menu')}
document.getElementById('menu-toggle').onclick=()=>{let nav=document.getElementById('nav'),open=nav.hidden;nav.hidden=!open;document.getElementById('menu-toggle').setAttribute('aria-expanded',String(open));document.getElementById('menu-toggle').setAttribute('aria-label',open?'Fechar menu':'Abrir menu')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();document.getElementById('menu-toggle').focus()}});document.addEventListener('click',e=>{if(!e.target.closest('#nav,#menu-toggle'))closeMenu()});

document.getElementById('filter-toggle').onclick=()=>{let b=document.getElementById('filter-body'),t=document.getElementById('filter-toggle');b.hidden=!b.hidden;t.setAttribute('aria-expanded',String(!b.hidden));t.querySelector('.chevron').textContent=b.hidden?'⌄':'⌃'};

let territoryMap=null,geoPromise=null,mapGeneration=0;
const AP_CITIES={'AP Bauru':['Bauru','Piratininga'],'AP São José do Rio Preto':['São José do Rio Preto','Mirassol','Bady Bassitt','Guapiaçu','Cedral'],'AP São José dos Campos':['São José dos Campos','Jacareí','Caçapava'],'AP Sorocaba':['Sorocaba','Votorantim','Araçoiaba da Serra','Alumínio']};
const mapAliases={'BRODOSQUI':'Brodowski','EMBU':'Embu das Artes','EUCLIDESDACUNHAPAULIST':'Euclides da Cunha Paulista','FLORINIA':'Florínea','IPAUCU':'Ipaussu','MOJIDASCRUZES':'Mogi das Cruzes','MOJIMIRIM':'Mogi Mirim','SANTARITADOPASSAQUATR':'Santa Rita do Passa Quatro','SANTOANTONIODOARACANGU':'Santo Antônio do Aracanguá','SAOLUISDOPARAITINGA':'São Luiz do Paraitinga'};
const mapName=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const canonicalMapName=s=>mapName(mapAliases[mapName(s)]||s);
function disposeTerritoryMap(){mapGeneration++;if(territoryMap){territoryMap.remove();territoryMap=null}}
async function initTerritoryMap(){const generation=mapGeneration,container=$('territory-map');try{if(!window.L)throw Error('Biblioteca do mapa indisponível');territoryMap=L.map(container,{scrollWheelZoom:false});const map=territoryMap;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors · Limites: IBGE'}).addTo(map).on('tileerror',()=>{if(generation===mapGeneration)$('map-selection').textContent+=' · Mapa-base indisponível; limites municipais preservados.'});const initialBounds=[[-26.273714024406416,-57.27172851562501],[-18.62542454070125,-42.03369140625001]];map.fitBounds(initialBounds);if(!geoPromise)geoPromise=fetch('assets/sp-municipios.geojson').then(r=>{if(!r.ok)throw Error('Limites indisponíveis');return r.json()}).catch(e=>{geoPromise=null;throw e});const geo=await geoPromise;if(generation!==mapGeneration)return;const p=params(),apNames=AP_CITIES[p.ap]||null,selected=geo.features.filter(f=>p.city?canonicalMapName(p.city)===mapName(f.properties.name):apNames?apNames.some(n=>canonicalMapName(n)===mapName(f.properties.name)):true);const layer=L.geoJSON({type:'FeatureCollection',features:selected},{style:{color:'#17657b',weight:1.5,fillColor:'#28758a',fillOpacity:(p.city||p.ap)?0.14:0.06},onEachFeature:(f,l)=>{const name=f.properties.name;l.bindTooltip(name,{sticky:true});const box=document.createElement('div');box.textContent=name;const originalCity=unique(ix.city).find(n=>canonicalMapName(n)===mapName(name));if(originalCity){const button=document.createElement('button');button.className='button';button.textContent='Selecionar município';button.onclick=()=>{$('city').value=originalCity;render()};box.append(document.createElement('br'),button)}else{const note=document.createElement('p');note.textContent='Sem município correspondente na base analítica.';box.append(note)}l.bindPopup(box)}}).addTo(map);const all=!p.city&&!p.ap;const label=p.city||p.ap||'Estado de São Paulo';$('map-selection').textContent=selected.length?`${label} · ${selected.length} ${selected.length===1?'município':'municípios'}`:`${label} · limite municipal sem correspondência`;const fit=()=>{if(all||!selected.length)map.fitBounds(initialBounds);else map.fitBounds(layer.getBounds(),{padding:[30,30],maxZoom:12})};fit();$('map-reset').onclick=fit;map.invalidateSize();}catch(e){if(generation===mapGeneration){$('map-selection').textContent='Não foi possível carregar o mapa. Reabra a página para tentar novamente.';console.error(e)}}}
